config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :works

  resources :works do
    member do
      post 'add_dig'
      delete 'remove_dig'
    end
  end

  root 'works#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, Work

    if user
      can [:add_dig, :remove_dig], Work
      can :create, Work
      can [:update, :destroy], Work do |work|
        user.id == work.user_id
      end
    end
  end
end

app/models/digged_work.rb
class DiggedWork < ActiveRecord::Base
  belongs_to :user
  belongs_to :work
end

app/models/home.rb
class Home < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :works, dependent: :destroy
  has_many :digged_works
  has_many :digs, class_name: 'Work', through: :digged_works, source: :work
  # has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  # validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

  def keeps (work)
    digs << work
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable
end

app/models/work.rb
class Work < ActiveRecord::Base
  belongs_to :user
  has_many :digged_works
  has_many :digged_by, class_name: 'User', through: :digged_works, source: :user


  #validates :public, { presence: true }
  validates :media_type, { presence: true }
  validates :info, { presence: true}
  validates :title, { presence: true }
  validates :artist, { presence: true }
  validates :year, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  rescue_from CanCan::AccessDenied, with: :access_denied

  private
  def access_denied
    redirect_to root_url, alert: "access denied"
  end
end

app/controllers/digged_work_controller.rb
class DiggedWorkController < ApplicationController
  load_and_authorize_resource

def index
  @digs = current_user.digged_works
end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @recent_works = Work.all.order(:created_at).limit(21)
  end

end

app/controllers/user_controller.rb
def create
  @user = User.create( user_params )
end

private

# Use strong_parameters for attribute whitelisting
# Be sure to update your create() and update() controller methods.

def user_params
  params.require(:user).permit(:avatar)
end

app/controllers/works_controller.rb
class WorksController < ApplicationController
  load_and_authorize_resource
  # before_action :set_work, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy, :add_dig, :remove_dig]

  def index
  end

  def show
  end

  def new
  end

  def create
    @work.user = current_user
    if @work.save
      redirect_to(work_path(@work))
    else
      render(:new)
    end
  end

  def edit
  end

  def update
    if @work.update(work_params)
      redirect_to(work_path(@work))
    else
      render(:edit)
    end
  end

  def destroy
    @work.destroy
    redirect_to(works_path)
  end

  def add_dig
    @work = Work.find(params[:id])
    @work.digged_works.create(user:current_user)
    redirect_to work_path(@work)
  end

  def remove_dig
    @work = Work.find(params[:id])
    @work.digged_works.where(user:current_user).destroy_all
    redirect_to work_path(@work)
  end

  private
  def work_params
    params.require(:work).permit(:title, :year, :artist, :media_type, :info)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<h1> w o r k s </h1>

<ul class="list-group">
  <% @recent_works.each do |work| %>
    <li class="list-group-item"><%= link_to work.title, work_path(work) %></li>
  <% end %>
</ul>
<% if can? :create, Work %>
<%= link_to "add work", new_work_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>D A P</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse navbar">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">digital art platform</a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <% if current_user %>
            <li><%= link_to 'Signout', destroy_user_session_path, :method => :delete %></li>

          <% else %>
            <li><%= link_to 'Signup', new_user_registration_path %></li>
        </ul>
    <ul class="nav navbar-nav navbar-right">
      <li>
        <%= link_to 'Login', new_user_session_path %>
        <% end %>
      </li>

    </ul>
  </div><!-- /.navbar-collapse -->
</div><!-- /.container-fluid -->
</nav>
<% if flash[:alert] %>

<div class="alert alert-danger" role="alert">
  <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
  <span class="sr-only"><%=flash[:alert]%></span>
  Enter a valid email address
</div>
<% end %>

<%= yield %>
</body>
</html>

app/views/users/edit.html.erb
<div class="center-block" style = "width:700px"><h1> y o u </h1>

  <%= simple_form_for @user, url: users_path do |form| %>
    <%= form.input :avatar, as: :file %>
  <% end %>

</div>

app/views/users/show.html.erb
<h1> w o r k s </h1>

<!-- <%= image_tag @user.avatar.url %>
<%= image_tag @user.avatar.url(:medium) %>
<%= image_tag @user.avatar.url(:thumb) %> -->

<ul class="list-group">
  <% @digs.each do |work| %>
    <li class="list-group-item"><%= link_to work.title, work_path(work) %></li>
  <% end %>
</ul>

app/views/works/_form.html.erb
<div class='col-sm-3 col-md-3'></div>
<div class='col-sm-6 col-md-6'>
<ul>
  <% @work.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
</ul>


<%= form_for @work do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :year %>
    <%= f.text_field :year %>
  </div>
  <div>
    <%= f.label :artist %>
    <%= f.text_field :artist %>
  </div>
  <div>
    <%= f.label :info %>
    <%= f.text_field :info %>
  </div>
  <div>
    <%= f.label :media_type %>
    <%= f.text_field :media_type %>
  </div class="btn-group">
  <%= f.submit class: "btn btn-default btn-sm"%>
<% end %>
</div>
<div class='col-sm-3 col-md-3'></div>

app/views/works/edit.html.erb
<div class="center-block" style = "width:700px"><h1> e d i t </h1>

<%= render "form" %>
<br>
<div class="btn-group">
<%= link_to "delete", work_path(@work), class: "btn btn-warning", method: :delete %>
</div>

</div>

app/views/works/index.html.erb
<div class="center-block" style = "width:400px"><h1></h1></div>
<br>
<div class="row">
  <% @works.each do |work| %>
    <div class="col-xs-6 col-md-3">
      <a href="#" class="thumbnail">
        <img src="<%= work.media_type %>">
        <%= link_to work.title, work_path(work) %>
      </a>
    </div>
  <% end %>

</div>

<br>
<br>

<div class="btn-group pull-right">
<% if can? :create, Work %>
<%= link_to "add work", new_work_path, class: "btn btn-default btn-sm" %>
<% end %>
</div>

app/views/works/new.html.erb
<div class='col-sm-3 col-md-3'></div>
<div class='col-sm-6 col-md-6'>
<h2> n e w </h2>

<%= render "form" %>

</div>
<div class='col-sm-3 col-md-3'></div>

app/views/works/show.html.erb
<div style="background-color:transparent !important">
<div class="center"><h2><%= @work.title %> (<%= @work.year %>)</h2></div>

<ul class="center-block" ><h3><%= @work.artist %></h3></ul>

<div class="left-block"><img src="<%= @work.media_type %>"></div>
<div class="right-block" style = "width:350px">
  <h6><%= @work.info %></h6>
</div>

  <div>
    <% if can? :add_dig, @work %>
      <% if @work.digged_works.where(user: current_user).length > 0 %>
        <%= link_to "&hearts;".html_safe, remove_dig_work_path(@work), method: :delete, class: "dig" %>
      <% else %>
        <%= link_to "&hearts;".html_safe, add_dig_work_path(@work), method: :post, class: "no-dig" %>
      <% end %>
    <% end %>
  </div>

<% if can? :update, @work %>
<div class="btn-group">
<%= link_to "edit", edit_work_path(@work), class: "btn btn-default btn-sm" %>
<% end %>
<tr>
<%= link_to "back", root_path(@work), class: "btn btn-default btn-sm" %>
</div>
</div>